// 100 korte, positieve ADHD-vriendelijke quotes over plannen & organiseren.
// (Bewust zonder auteurs/attributie; puur originele/algemene motivatietekst.)

export const ADHD_PLANNING_QUOTES: string[] = [
  "Eén lijstje is een externe hersenschijf — gebruik ‘m.",
  "Klein plan, grote rust.",
  "Begin met de volgende stap, niet met het hele project.",
  "Je hoeft het niet perfect te doen om het af te maken.",
  "Een timer is geen druk, het is een vangrail.",
  "Structuur is vriendelijk: het maakt ruimte in je hoofd.",
  "Eerst duidelijkheid, dan snelheid.",
  "Een micro-stap is ook vooruitgang.",
  "Je aandacht volgt je omgeving — maak het makkelijk.",
  "Plan minder, doe meer: kies één focusblok.",
  "Vandaag is een serie kleine overwinningen.",
  "Kies de kleinste ‘ja’ die je nu kunt doen.",
  "Als het vaag is, split het op.",
  "Zet het op papier, dan hoeft je brein het niet te dragen.",
  "Eerst starten, daarna optimaliseren.",
  "Je bent niet laat; je bent onderweg.",
  "Maak het zichtbaar, maak het haalbaar.",
  "Een korte sprint is vaak beter dan een lange worsteling.",
  "Rustige taken tellen ook mee.",
  "Focus is trainen, niet bewijzen.",
  "Herinneringen zijn hulpmiddelen, geen oordeel.",
  "Je planning is een vriend, geen politieagent.",
  "Leg de lat: ‘done is done’.",
  "Eén ding tegelijk is superkracht.",
  "Schrap om te kunnen winnen.",
  "Als het zwaar voelt: maak het kleiner.",
  "Eerst 5 minuten. Dan zien we verder.",
  "Je hoeft niet gemotiveerd te zijn om te beginnen.",
  "Organiseren is vooruitdenken voor je toekomstige zelf.",
  "Laat je agenda je energie beschermen.",
  "Een pauze is onderdeel van het plan.",
  "Kies één startpunt en maak het af.",
  "Je brein houdt van duidelijkheid — geef het labels.",
  "Alles opschrijven is zelfzorg.",
  "Prioriteit = wat je nu niet hoeft te doen.",
  "Een check-in is een resetknop.",
  "Korte taken eerst geeft momentum.",
  "Momentum is planning in actie.",
  "Je hoeft alleen de volgende stap te zien.",
  "Plan je start, niet je hele dag.",
  "Maak frictie kleiner, resultaat groter.",
  "Herhaalbare routines winnen van wilskracht.",
  "Je energie bepaalt de taak, niet andersom.",
  "Als je twijfelt: kies ‘makkelijk’ en ga door.",
  "Een timer maakt je grenzen zichtbaar.",
  "Klaar is beter dan perfect.",
  "Eén blok focus is al een win.",
  "Een lijst is een contract met rust.",
  "Kleine deadlines, grote helderheid.",
  "Vang afleidingen op, laat ze niet sturen.",
  "Parkeer gedachten, niet je voortgang.",
  "Eerst ordenen, dan uitvoeren.",
  "Je hoeft het niet te voelen om het te doen.",
  "Maak je volgende actie belachelijk simpel.",
  "Een plan is een gok; bijsturen is de skill.",
  "Je mag herstarten zonder te falen.",
  "Je aandacht is kostbaar — geef het richting.",
  "Werk met je brein, niet tegen je brein.",
  "Kies één ding dat vandaag ‘goed genoeg’ is.",
  "Simpel is niet minderwaardig; simpel is werkbaar.",
  "Elke afgeronde taak is bewijs van progressie.",
  "Geef je taak een beginpunt.",
  "Maak ‘later’ een plek, geen stress.",
  "Je planning is een kaart, geen gevangenis.",
  "Als het niet past, verklein het blok.",
  "Stop met alles onthouden; begin met alles noteren.",
  "Een duidelijke titel is halve organisatie.",
  "Start waar je bent, met wat je hebt.",
  "Een stapje nu scheelt 10 later.",
  "Kies wat het meeste rust oplevert.",
  "Je brein houdt van beloningen — gebruik XP slim.",
  "Korte focus, lange impact.",
  "Eén taak afronden > tien taken aanraken.",
  "Maak ruimte voor ‘niet vandaag’.",
  "Je hoeft niet alles; je kiest bewust.",
  "Een kleine overwinning maakt de volgende makkelijker.",
  "Tijd is een hulpmiddel: zet het in je voordeel.",
  "Je hebt geen perfecte dag nodig voor progressie.",
  "Als het teveel is: timer aan, wereld uit.",
  "Je agenda is een schild tegen chaos.",
  "Stap voor stap is ook een strategie.",
  "Maak je werk zichtbaar en het wordt lichter.",
  "Je mag pauzeren zonder schuld.",
  "Kies één einde: wanneer is het ‘klaar’?",
  "Een goede planning ademt: er is ruimte.",
  "Je focus verdient bescherming.",
  "Eerst afronden, dan toevoegen.",
  "Voorspelbaarheid geeft rust.",
  "Je hoeft niet sneller; je hoeft duidelijker.",
  "Een klein blok is een win die je kunt volhouden.",
  "Een lijstje is liefde voor je toekomstige zelf.",
  "Je bent niet je afleiding; je bent je keuze.",
  "Herhaal wat werkt, laat de rest los.",
  "Organiseren is kiezen wat je niet hoeft te dragen.",
  "Elke keer dat je terugkomt, bouw je focus-spier.",
  "Eén prioriteit vandaag is genoeg.",
  "Je hoeft niet alles te doen om trots te zijn.",
  "Kies rust als uitgangspunt.",
  "Vandaag: klein, helder, haalbaar.",
  "Je planning mag meebewegen met je energie.",
];

export function getRandomAdhdPlanningQuote(seed?: number): string {
  const n = ADHD_PLANNING_QUOTES.length;
  if (n === 0) return "Kleine stap. Grote winst.";
  const idx = typeof seed === 'number'
    ? Math.abs(Math.floor(seed)) % n
    : Math.floor(Math.random() * n);
  return ADHD_PLANNING_QUOTES[idx];
}


