// 100 korte complimenten/tips als beloning na het afronden van een taak.
// Doel: gedrag bekrachtigen (ADHD-vriendelijk), positief, concreet, niet belerend.

export const COMPLETION_REWARDS: string[] = [
  "Je hebt het afgemaakt. Dat is de skill.",
  "Goed gedaan. Klaar = ruimte in je hoofd.",
  "Yes! Je hebt jezelf zojuist een beetje rust gegeven.",
  "Dit is momentum. Pak dat mee.",
  "Afgerond is een overwinning, hoe klein ook.",
  "Je brein onthoudt dit: afronden loont.",
  "Je hebt gedaan wat je zei dat je zou doen. Sterk.",
  "Klaar. Adem in. Door.",
  "Nice. Je hebt frictie omgezet in actie.",
  "Dit is bewijs: je kunt taken afronden.",
  "Goed bezig, één taak minder om te dragen.",
  "Je hebt jezelf geholpen. Dat telt.",
  "Top. Volhouden is gebouwd uit dit soort momenten.",
  "Je hebt een eindpunt gezet. Dat is volwassen focus.",
  "Je hebt het afgerond zonder te wachten op 'perfect'.",
  "Dit is hoe routines ontstaan: herhalen wat werkt.",
  "Je hebt je aandacht teruggewonnen. Lekker.",
  "Mooi. Je hebt jezelf niet laten afleiden van 'done'.",
  "Je hebt het afgemaakt. Dat is het belangrijkste.",
  "Winst: je hoeft hier vandaag niet meer aan te denken.",
  "Goed gedaan. Neem 10 seconden om het te voelen.",
  "Je bouwt vertrouwen op met elke 'klaar'.",
  "Klaar is een cadeautje aan je toekomstige zelf.",
  "Je hebt je plan gevolgd. Respect.",
  "Je bent consistent aan het worden. Merk je het?",
  "Deze taak is nu van de lijst. Punt.",
  "Je hebt jezelf een mini-beloning verdiend.",
  "Je maakt progressie zichtbaar. Dat motiveert.",
  "Sterk: je rondt af in plaats van te blijven schuiven.",
  "Je hebt je focus gespierd. Goed werk.",
  "Je doet dit. Echt.",
  "Je hebt het afgerond. En dat is niet 'klein'.",
  "Je brein houdt van afronden. Geef 't meer hiervan.",
  "Je hebt gewonnen van uitstel. Nice.",
  "Top. Pak nu de makkelijkste volgende stap.",
  "Je mag trots zijn. Klaar is klaar.",
  "Dit is hoe je dagen lichter maakt: één taak tegelijk.",
  "Je hebt je aandacht goed gebruikt. Lekker bezig.",
  "Je hebt jezelf niet laten afleiden door 'nog even'.",
  "Je bent vooruit gegaan, niet rondjes gedraaid.",
  "Goed gedaan. Je hebt jezelf structuur gegeven.",
  "Afgerond = minder mentale ruis.",
  "Je hebt iets afgesloten. Dat geeft rust.",
  "Je hebt het gedaan. Dat was het werk.",
  "Je hebt je focus terugbetaald met resultaat.",
  "Mooi. Je hebt de finish gehaald.",
  "Je hebt je energie slim ingezet.",
  "Je hebt gedaan wat nodig was. Punt.",
  "Je maakt ruimte voor de volgende overwinning.",
  "Je hebt jezelf geholpen met een duidelijke 'klaar'.",
  "Je bent betrouwbaarder dan je brein soms zegt.",
  "Dit is discipline in vriendelijke vorm.",
  "Je hoeft het niet te voelen om het te doen. Kijk maar.",
  "Je hebt een stap gezet richting rust.",
  "Sterk werk. Even mini-pauze, dan door.",
  "Je bouwt een streak van afronden.",
  "Je hebt jezelf niet opgegeven. Goed.",
  "Je hebt de taak klein genoeg gemaakt om te finishen.",
  "Dit is precies hoe je vooruit komt.",
  "Klaar. Check. Volgende.",
  "Je hebt gekozen voor actie. Goed besluit.",
  "Je laat je brein zien dat je kunt afronden.",
  "Goed bezig. Vier het heel even.",
  "Je hoeft niet 10 dingen te doen. Eén 'done' is goud.",
  "Je hebt je aandacht beschermd. Dat is een skill.",
  "Je hebt je planning laten werken vóór je.",
  "Dit is hoe je zelfvertrouwen opbouwt: afronden.",
  "Je hebt het afgerond. Dat is een win voor morgen.",
  "Je hebt het gedaan met het brein dat je hebt. Sterk.",
  "Je bent aan het trainen. En het werkt.",
  "Klaar. Dat betekent: ruimte, rust, verder.",
  "Je hebt je doel gehaald. Respect.",
  "Je hebt een 'open loop' gesloten. Heerlijk.",
  "Je hebt de stap afgemaakt. Dat is focus.",
  "Goed gedaan. Even water, dan door.",
  "Je hebt je aandacht omgezet in resultaat.",
  "Je bent niet je afleiding, je bent je keuze. Mooi.",
  "Je hebt je eigen systeem gevolgd. Dat is groei.",
  "Je brein krijgt een beloning: 'klaar'.",
  "Je hebt jezelf serieus genomen. Goed.",
  "Je hebt dit afgerond ondanks alles. Sterk.",
  "Je maakt je dag overzichtelijker. Nice.",
  "Je hebt tijd gekocht voor jezelf: minder later-stress.",
  "Je hebt je focus een plek gegeven en het afgemaakt.",
  "Goed werk. Houd dit ritme vast.",
  "Je hebt het gedaan. Volgende stap mag klein zijn.",
  "Je laat consistentie zien. Dat is kracht.",
  "Je hebt een duidelijke finish gemaakt. Mooi.",
  "Je hebt gedaan wat je moest doen. Zonder drama.",
  "Dit is hoe je doelen haalt: afronden, herhalen.",
  "Je hebt je brein een succesmoment gegeven.",
  "Je hebt je aandacht teruggepakt. Top.",
  "Je hebt de taak afgesloten. Je mag loslaten.",
  "Goed gedaan. Hou dit vast: klein → klaar.",
  "Je hebt het afgemaakt. Dat is leiderschap over je dag.",
  "Je hebt het gedaan. En dat telt.",
  "Je bent aan het bouwen aan een betere standaard.",
  "Je hebt een nieuwe 'baseline' gezet: jij rondt af.",
  "Je hebt gewonnen. Volgende.",
  "Je hebt iets afgerond. Dat is altijd de moeite waard.",
  "Je hebt je focus goed gebruikt. Trots moment.",
  "Je brein krijgt signalen: 'we kunnen dit'.",
  "Je hebt je tijd gerespecteerd door af te ronden.",
  "Je hebt het gedaan. Neem die XP met trots.",
];

export function getRandomCompletionReward(seed?: number): string {
  const n = COMPLETION_REWARDS.length;
  if (n === 0) return "Goed gedaan, kleine stap, grote winst.";
  const idx = typeof seed === 'number'
    ? Math.abs(Math.floor(seed)) % n
    : Math.floor(Math.random() * n);
  return COMPLETION_REWARDS[idx];
}
