import { getDayOfYearAmsterdam } from "@/lib/dagstartCookie";

export const DAY_START_QUOTES_NL: readonly string[] = [
  "Je hoeft vandaag niet alles. Je hoeft alleen dit.",
  "Een brein dat veel voelt, heeft ook veel te geven.",
  "Beginnen is het moeilijkste. De rest volgt vanzelf.",
  "Structuur is geen kooi. Het is de reling op de trap.",
  "Je bent niet lui. Je brein zoekt gewoon de juiste prikkel.",
  "Eén taak afmaken is meer waard dan tien taken starten.",
  "ADHD is geen gebrek aan aandacht. Het is aandacht zonder rem.",
  "Vandaag hoeft niet perfect te zijn. Vandaag moet alleen beginnen.",
  "Je energie is geen fout. Het is een signaal.",
  "Het mooie van elke dag: hij begint opnieuw.",
  "Dopamine volgt actie. Niet andersom.",
  "Klein beginnen is geen falen. Het is slim plannen.",
  "Je brein is snel. Geef het één richting.",
  "Niet alles wat wacht, verdwijnt. Begin met wat telt.",
  "Rust nemen is geen verspilling. Het is brandstof.",
  "Jij bent niet je to-do lijst.",
  "Een dag met één voltooide taak is een geslaagde dag.",
  "Het gaat niet om hoeveel je doet. Het gaat om wat je kiest.",
  "Je bent goed genoeg voor vandaag. Precies zoals je nu bent.",
  "Fouten zijn data. Geen bewijs van falen.",
  "Jouw brein ziet verbanden die anderen missen.",
  "Energie fluctueert. Dat is menselijk, geen tekortkoming.",
  "De motor start niet altijd meteen. Geef hem even.",
  "Wat je vandaag begint, hoef je morgen niet opnieuw op te starten.",
  "Chaos is niet wie je bent. Het is waar je vandaan komt.",
  "Micro-stappen zijn geen kleine stappen. Het zijn slimme stappen.",
  "Je focus is kostbaar. Kies bewust waar je hem op richt.",
  "Ochtenden zijn moeilijk. Jij ook. Allebei de moeite waard.",
  "Het enige wat telt: wat doe je nú.",
  "Je hebt gisteren overleefd. Vandaag ook.",
  "ADHD betekent: je voelt meer, je denkt sneller, je leeft intenser.",
  "Niet elke dag is hetzelfde. Dat is een voordeel, geen probleem.",
  "Jij bepaalt wat belangrijk is. Niet de lijst.",
  "Beginnen met iets kleins is niet zwak. Het is wijs.",
  "Jouw tempo is jouw tempo. Vergelijk het met niets.",
  "Een plan is een richting, geen verplichting.",
  "Je brein heeft rust nodig om goed te presteren. Geef het die rust.",
  "Vandaag is een nieuwe poging. Elke dag is dat.",
  "Het lukt niet altijd. Dat hoeft ook niet altijd.",
  "Wat klein lijkt, is soms het grootste wat je vandaag kunt doen.",
  "Soms is stilstaan de meest productieve keuze.",
  "Je aandacht gaat waar je zorg naartoe. Kies bewust.",
  "Overprikkeling is geen zwakte. Het is een signaal om te vertragen.",
  "Je hoeft niets te bewijzen vandaag.",
  "Eén beslissing is genoeg om de dag in beweging te zetten.",
  "Vergeten hoort bij een druk brein. Systemen zijn geen luxe.",
  "Je bent niet achter. Je bent op een ander spoor.",
  "Wat je niet doet, is ook een keuze.",
  "Impulsen zijn informatie. Je hoeft ze niet altijd te volgen.",
  "Langzaam starten is nog steeds starten.",
  "Je waarde staat los van je productiviteit.",
  "Het is oké als je brein eerst moet opwarmen.",
  "Prioriteit kiezen is al half het werk.",
  "Niet alles vraagt om aandacht vandaag.",
  "Je mag iets laten vallen zonder jezelf te laten vallen.",
  "Een korte focus kan meer opleveren dan uren half-aan.",
  "Je lichaam weet vaak eerder dan je hoofd wat je nodig hebt.",
  "Vandaag telt. Ook als het rustig blijft.",
  "Je hoeft niet te inhalen wat gisteren niet lukte.",
  "Heldere keuzes maken de dag lichter.",
  "Je brein werkt hard, ook als het stil lijkt.",
  "Kleine overwinningen tellen mee.",
  "Structuro helpt je kiezen. Jij hoeft niet alles te dragen.",
  "Eén ding tegelijk is geen beperking. Het is stevige grond.",
  "Je mag beginnen zonder zeker te weten hoe het eindigt.",
  "Soms is het grootste werk: jezelf toestemming geven.",
  "Je aandacht springt. Dat maakt je ook creatief.",
  "Niet elke taak verdient je beste energie.",
  "Wat je vandaag niet doet, kan morgen nog steeds belangrijk zijn.",
  "Je bent niet je slechtste dag.",
  "Een rustige start kan een sterke dag worden.",
  "Je brein zoekt betekenis. Geef het één duidelijk doel.",
  "Het is oké als je eerst moet landen.",
  "Je hoeft niet meteen in topvorm te zijn.",
  "Focus is een hulpbron, geen karaktereigenschap.",
  "Je mag je energie beschermen.",
  "Wat je start, hoef je niet vandaag af te maken.",
  "Je bent al bezig met vooruitgang door hier te zijn.",
  "Een lijst is een hulpmiddel, geen oordeel.",
  "Je brein heeft patronen nodig, geen druk.",
  "Vandaag mag anders zijn dan je dacht.",
  "Je hoeft niet alles te onthouden. Daar is Structuro voor.",
  "Eén heldere stap maakt de rest overzichtelijker.",
  "Je mag moe zijn zonder iets mis te doen.",
  "Niet alles wat urgent lijkt, is belangrijk.",
  "Je aandacht is breed. Dat heeft ook waarde.",
  "Begin klein als groot te zwaar voelt.",
  "Je hoeft vandaag geen held te zijn.",
  "Wat je voltooit, telt meer dan wat je plant.",
  "Je brein reageert op nu. Maak nu klein genoeg.",
  "Het is oké als je eerst structuur nodig hebt.",
  "Je mag je dag aanpassen aan je energie.",
  "Soms is doorzetten minder wijs dan pauzeren.",
  "Je bent niet inconsistent. Je bent levend.",
  "Eén taak minder kan de dag dragelijk maken.",
  "Je focus komt vaak ná de eerste actie.",
  "Het helpt om te kiezen wat vandaag echt telt.",
  "Je brein zoekt prikkels. Kies er één die helpt.",
  "Je mag langzaam zijn en toch vooruit.",
  "Niet alles hoeft vandaag af.",
  "Je waard bent er al, vóór je eerste taak.",
  "Een goede dag hoeft niet vol te zitten.",
  "Je hoeft niet te multitasken om waardevol te zijn.",
  "Wat je nu kiest, geeft richting aan de rest.",
  "Je brein kan veel. Geef het één duidelijke opdracht.",
  "Het is oké als je eerst moet ordenen.",
  "Je mag je grenzen respecteren.",
  "Kleine stappen stapelen op.",
  "Je bent niet je afleiding.",
  "Vandaag is genoeg tijd voor wat past.",
  "Je aandacht is kostbaar. Besteed hem bewust.",
  "Soms is het winnen: niet opgeven aan alles tegelijk.",
  "Je brein heeft tijd nodig om te schakelen.",
  "Eén focuspunt maakt de dag hanteerbaar.",
  "Je mag beginnen zonder perfecte omstandigheden.",
  "Niet alles vraagt om directe actie.",
  "Je energie mag laag zijn zonder verklaring.",
  "Wat je vandaag doet, hoeft niet alles op te lossen.",
  "Je bent capabel, ook op rustige dagen.",
  "Structuur geeft ruimte, geen straf.",
  "Je hoeft niet alles alleen te dragen.",
  "Eén keuze kan de rest van de dag verlichten.",
  "Je brein leert door doen, niet door wachten op motivatie.",
  "Het is oké als je plan verandert.",
  "Je mag trots zijn op kleine stappen.",
  "Niet elke dag hoeft productief te voelen.",
  "Je aandacht is actief, ook als het niet zichtbaar is.",
  "Begin met wat haalbaar voelt.",
  "Je hoeft niet te racen tegen je eigen brein.",
  "Wat je vandaag kiest, is genoeg.",
  "Je brein zoekt betekenis in chaos. Geef het één anker.",
  "Rust is onderdeel van vooruitgang.",
  "Je mag je dag klein houden.",
  "Eén taak af is beter dan drie half open.",
  "Je bent niet te veel. Je systeem was te weinig.",
  "Vandaag mag zacht beginnen.",
  "Je focus hoeft niet lang. Alleen duidelijk.",
  "Het helpt om eerst te voelen, dan te kiezen.",
  "Je brein reageert op helderheid.",
  "Je mag iets uitstellen zonder te falen.",
  "Niet alles wat je denkt, moet vandaag gebeuren.",
  "Je waarde verandert niet door je energie.",
  "Eén richting is genoeg voor nu.",
  "Je hoeft niet alles tegelijk te begrijpen.",
  "Kleine helderheid is ook helderheid.",
  "Je brein werkt beter met compassie dan met druk.",
  "Vandaag is een nieuwe kans om het anders te doen.",
  "Je mag je tempo kiezen.",
  "Wat je start, mag klein zijn.",
  "Je aandacht is geen defect.",
  "Soms is het beste: één ding afmaken.",
  "Je brein heeft een aanloop nodig. Dat is normaal.",
  "Je hoeft niet meteen alles te weten.",
  "Eén keuze geeft rust in je hoofd.",
  "Je mag je energie eerlijk benoemen.",
  "Niet elke taak is voor vandaag.",
  "Je bent al verder dan je denkt.",
  "Structuur helpt je brein landen.",
  "Je mag beginnen voordat je er zin in hebt.",
  "Wat telt, is wat je vandaag echt doet.",
  "Je brein zoekt snelheid. Jij kiest richting.",
  "Het is oké als vandaag simpel blijft.",
  "Je hoeft niet alles te fixen.",
  "Eén stap maakt de volgende lichter.",
  "Je aandacht verdient een doel dat past.",
  "Je mag je dag aanpassen, niet jezelf wegcijferen.",
  "Niet alles hoeft zwaar te voelen.",
  "Je brein is gevoelig. Dat maakt je ook scherp.",
  "Vandaag is genoeg.",
  "Je hoeft niet perfect te starten.",
  "Eén focuspunt is al een overwinning.",
  "Je mag rust nemen zonder schuldgevoel.",
  "Wat je nu kiest, helpt je brein ontspannen.",
  "Je bent niet je uitstelgedrag.",
  "Kleine actie kan grote verlichting geven.",
  "Je brein heeft een anker nodig. Kies er één.",
  "Het is oké als je eerst moet ademen.",
  "Je mag je dag op maat maken.",
  "Niet alles wat je voelt, is een opdracht.",
  "Je waarde zit niet in je output.",
  "Eén heldere keuze is genoeg om te beginnen.",
  "Je brein reageert op wat concreet is.",
  "Vandaag hoef je niet alles te dragen.",
  "Je mag langzaam vooruit zonder achter te lopen.",
  "Wat je vandaag doet, mag genoeg zijn.",
  "Je aandacht is krachtig als je hem richt.",
  "Soms is het belangrijkste: beginnen met één ding.",
  "Je brein zoekt zekerheid. Geef het één stap.",
  "Je hoeft niet alles tegelijk op te lossen.",
  "Eén taak kan de dag dragen.",
  "Je mag je energie volgen in plaats van ertegen te vechten.",
  "Niet elke dag vraagt hetzelfde van je.",
  "Je bent capabel op jouw manier.",
  "Structuur is steun, geen controle.",
  "Je mag vandaag klein beginnen en toch ver komen.",
  "Wat je kiest, is belangrijker dan hoeveel je doet.",
  "Je brein heeft compassie nodig om te presteren.",
  "Het is oké als je eerst moet landen in je dag.",
  "Je hoeft niet alles te bewijzen aan jezelf.",
  "Eén duidelijke start is genoeg."
];

export const DAY_START_QUOTES_EN: readonly string[] = [
  "You do not need to do everything today. Only this.",
  "A brain that feels deeply also has a lot to give.",
  "Starting is the hardest part. The rest follows.",
  "Structure is not a cage. It is the handrail on the stairs.",
  "You are not lazy. Your brain is looking for the right cue.",
  "Finishing one task beats starting ten.",
  "ADHD is not a lack of attention. It is attention without brakes.",
  "Today does not need to be perfect. It only needs to begin.",
  "Your energy is not a flaw. It is a signal.",
  "Every day starts again. That is the good part.",
  "Dopamine follows action. Not the other way around.",
  "Starting small is not failing. It is smart planning.",
  "Your brain is fast. Give it one direction.",
  "Not everything waiting will disappear. Start with what matters.",
  "Rest is not wasted time. It is fuel.",
  "You are not your to-do list.",
  "A day with one completed task is a successful day.",
  "It is not about how much you do. It is about what you choose.",
  "You are enough for today. Exactly as you are now.",
  "Mistakes are data. Not proof of failure.",
  "Your brain sees connections others miss.",
  "Energy fluctuates. That is human, not a defect.",
  "The engine does not always start right away. Give it a moment.",
  "What you start today does not need a cold start tomorrow.",
  "Chaos is not who you are. It is where you come from.",
  "Micro-steps are not small steps. They are smart steps.",
  "Your focus is precious. Choose where it goes.",
  "Mornings are hard. So are you. Both are worth it.",
  "All that matters is what you do now.",
  "You survived yesterday. Today too.",
  "ADHD means you feel more, think faster, live more intensely.",
  "Not every day is the same. That is an advantage.",
  "You decide what matters. Not the list.",
  "Starting small is not weak. It is wise.",
  "Your pace is your pace. Compare it to nothing.",
  "A plan is a direction, not a contract.",
  "Your brain needs rest to perform well. Give it that rest.",
  "Today is a new attempt. Every day is.",
  "It does not always work. That is allowed too.",
  "What looks small may be the biggest thing you can do today.",
  "Sometimes stillness is the most productive choice.",
  "Your attention goes where your worry goes. Choose on purpose.",
  "Overstimulation is not weakness. It is a signal to slow down.",
  "You do not need to prove anything today.",
  "One decision is enough to set the day in motion.",
  "Forgetting belongs to a busy brain. Systems are not a luxury.",
  "You are not behind. You are on a different track.",
  "What you do not do is also a choice.",
  "Impulses are information. You do not have to follow them.",
  "Starting slowly is still starting.",
  "Your worth is separate from your productivity.",
  "It is okay if your brain needs to warm up first.",
  "Choosing a priority is already half the work.",
  "Not everything needs your attention today.",
  "You can drop something without dropping yourself.",
  "A short focus can beat hours of half-attention.",
  "Your body often knows before your head what you need.",
  "Today counts. Even if it stays quiet.",
  "You do not need to catch up on yesterday.",
  "Clear choices make the day lighter.",
  "Your brain works hard, even when it looks still.",
  "Small wins count.",
  "Structuro helps you choose. You do not carry everything alone.",
  "One thing at a time is not a limit. It is solid ground.",
  "You can start without knowing how it ends.",
  "Sometimes the biggest work is giving yourself permission.",
  "Your attention jumps. That also makes you creative.",
  "Not every task deserves your best energy.",
  "What you skip today can still matter tomorrow.",
  "You are not your worst day.",
  "A calm start can become a strong day.",
  "Your brain seeks meaning. Give it one clear goal.",
  "It is okay if you need to land first.",
  "You do not need to be in top shape immediately.",
  "Focus is a resource, not a character trait.",
  "You are allowed to protect your energy.",
  "What you start does not have to finish today.",
  "You are already making progress by being here.",
  "A list is a tool, not a verdict.",
  "Your brain needs patterns, not pressure.",
  "Today may look different than you thought.",
  "You do not need to remember everything. That is what Structuro is for.",
  "One clear step makes the rest easier to see.",
  "You can be tired without doing something wrong.",
  "Not everything urgent is important.",
  "Your attention is broad. That has value too.",
  "Start small when big feels too heavy.",
  "You do not need to be a hero today.",
  "What you finish matters more than what you plan.",
  "Your brain responds to now. Make now small enough.",
  "It is okay if you need structure first.",
  "You can shape your day around your energy.",
  "Sometimes pausing is wiser than pushing.",
  "You are not inconsistent. You are alive.",
  "One fewer task can make the day bearable.",
  "Focus often comes after the first action.",
  "It helps to choose what truly counts today.",
  "Your brain seeks stimulation. Pick one that helps.",
  "You can be slow and still move forward.",
  "Not everything has to finish today.",
  "Your worth exists before your first task.",
  "A good day does not have to be full.",
  "You do not need to multitask to be valuable.",
  "What you choose now gives direction to the rest.",
  "Your brain can do a lot. Give it one clear job.",
  "It is okay if you need to organize first.",
  "You are allowed to respect your limits.",
  "Small steps stack up.",
  "You are not your distraction.",
  "Today is enough time for what fits.",
  "Your attention is precious. Spend it on purpose.",
  "Sometimes winning means not giving in to everything at once.",
  "Your brain needs time to switch gears.",
  "One focus point makes the day manageable.",
  "You can start without perfect conditions.",
  "Not everything needs immediate action.",
  "Your energy can be low without explanation.",
  "What you do today does not have to solve everything.",
  "You are capable, even on quiet days.",
  "Structure creates space, not punishment.",
  "You do not need to carry everything alone.",
  "One choice can lighten the rest of the day.",
  "Your brain learns by doing, not by waiting for motivation.",
  "It is okay if your plan changes.",
  "You can be proud of small steps.",
  "Not every day has to feel productive.",
  "Your attention is active, even when it is invisible.",
  "Start with what feels doable.",
  "You do not need to race your own brain.",
  "What you choose today is enough.",
  "Your brain seeks meaning in chaos. Give it one anchor.",
  "Rest is part of progress.",
  "You can keep your day small.",
  "One finished task beats three half-open ones.",
  "You are not too much. Your system was too little.",
  "Today can begin softly.",
  "Your focus does not need to be long. Only clear.",
  "It helps to feel first, then choose.",
  "Your brain responds to clarity.",
  "You can postpone something without failing.",
  "Not every thought has to become a task today.",
  "Your worth does not change with your energy.",
  "One direction is enough for now.",
  "You do not need to understand everything at once.",
  "Small clarity is still clarity.",
  "Your brain works better with compassion than pressure.",
  "Today is another chance to do it differently.",
  "You can choose your pace.",
  "What you start can be small.",
  "Your attention is not broken.",
  "Sometimes the best move is finishing one thing.",
  "Your brain needs a runway. That is normal.",
  "You do not need to know everything right away.",
  "One choice brings quiet to your head.",
  "You can name your energy honestly.",
  "Not every task is for today.",
  "You are further along than you think.",
  "Structure helps your brain land.",
  "You can start before you feel like it.",
  "What counts is what you actually do today.",
  "Your brain seeks speed. You choose direction.",
  "It is okay if today stays simple.",
  "You do not need to fix everything.",
  "One step makes the next one lighter.",
  "Your attention deserves a goal that fits.",
  "You can adjust your day without erasing yourself.",
  "Not everything has to feel heavy.",
  "Your brain is sensitive. That also makes you sharp.",
  "Today is enough.",
  "You do not need a perfect start.",
  "One focus point is already a win.",
  "You can rest without guilt.",
  "What you choose now helps your brain settle.",
  "You are not your procrastination.",
  "A small action can bring big relief.",
  "Your brain needs an anchor. Pick one.",
  "It is okay if you need to breathe first.",
  "You can tailor your day.",
  "Not everything you feel is an assignment.",
  "Your value is not your output.",
  "One clear choice is enough to begin.",
  "Your brain responds to what is concrete.",
  "Today does not need to carry everything.",
  "You can move slowly without falling behind.",
  "What you do today can be enough.",
  "Your attention is powerful when directed.",
  "Sometimes what matters most is starting one thing.",
  "Your brain seeks certainty. Give it one step.",
  "You do not need to solve everything at once.",
  "One task can carry the day.",
  "You can follow your energy instead of fighting it.",
  "Not every day asks the same of you.",
  "You are capable in your own way.",
  "Structure is support, not control.",
  "You can start small today and still go far.",
  "What you choose matters more than how much you do.",
  "Your brain needs compassion to perform.",
  "It is okay if you need to land in your day first.",
  "You do not need to prove anything to yourself.",
  "One clear start is enough."
];

export function getDayStartQuotesForLocale(locale: string): readonly string[] {
  return locale === "en" ? DAY_START_QUOTES_EN : DAY_START_QUOTES_NL;
}

export function getDayStartQuoteForLocale(locale: string, now: Date = new Date()): string {
  const quotes = getDayStartQuotesForLocale(locale);
  const dayOfYear = getDayOfYearAmsterdam(now);
  return quotes[dayOfYear % quotes.length] ?? quotes[0];
}
