export type EnergyDoneLevel = "low" | "medium" | "high";

const KEYS: Record<EnergyDoneLevel, string> = {
  low: "structuro_energy_done_idx_low",
  medium: "structuro_energy_done_idx_medium",
  high: "structuro_energy_done_idx_high",
};

const LOW_QUOTES: string[] = [
  "Rustig aan vandaag is een slimme keuze, en dat is oké.",
  "Je tempo mag vandaag zacht zijn, en dat is oké.",
  "Lage energie vraagt om zachte grenzen, en dat is oké.",
  "Kleine stappen zijn vandaag genoeg, en dat is oké.",
  "Je hoeft vandaag niet te bewijzen hoeveel je aankunt, en dat is oké.",
  "Een rustige dag is ook een goede dag, en dat is oké.",
  "Luister naar wat je lichaam vandaag fluistert, en dat is oké.",
  "Minder doen is soms de beste planning, en dat is oké.",
  "Je mag vandaag ruimte houden voor herstel, en dat is oké.",
  "Zachtheid naar jezelf is vandaag goud waard, en dat is oké.",
  "Geen sprint nodig, een wandeling mag ook, en dat is oké.",
  "Vandaag telt mee, ook als het stil voelt, en dat is oké.",
  "Je bent waardevol, ook op een stille modus, en dat is oké.",
  "Rust hoort bij je systeem, ook op een werkdag, en dat is oké.",
  "Je brein vraagt om lucht, geef het die ruimte, en dat is oké.",
  "Eén ding met aandacht is meer dan genoeg, en dat is oké.",
  "Je mag nee zeggen tegen extra ballast vandaag, en dat is oké.",
  "Langzaam voelen is geen mislukking, en dat is oké.",
  "Vandaag mag je kiezen voor wat haalbaar voelt, en dat is oké.",
  "Je hoeft niet op te laden voor de hele week, alleen voor nu, en dat is oké.",
  "Een zachte start is ook een start, en dat is oké.",
  "Je energie is informatie, geen oordeel, en dat is oké.",
  "Minder prikkels vandaag is zelfzorg, en dat is oké.",
  "Je mag prioriteit geven aan wat rust geeft, en dat is oké.",
  "Het is oké als vandaag vooral over ademen gaat, en dat is oké.",
  "Rustig aan vandaag is een slimme keuze, zonder schuld.",
  "Je tempo mag vandaag zacht zijn, zonder schuld.",
  "Lage energie vraagt om zachte grenzen, zonder schuld.",
  "Kleine stappen zijn vandaag genoeg, zonder schuld.",
  "Je hoeft vandaag niet te bewijzen hoeveel je aankunt, zonder schuld.",
  "Een rustige dag is ook een goede dag, zonder schuld.",
  "Luister naar wat je lichaam vandaag fluistert, zonder schuld.",
  "Minder doen is soms de beste planning, zonder schuld.",
  "Je mag vandaag ruimte houden voor herstel, zonder schuld.",
  "Zachtheid naar jezelf is vandaag goud waard, zonder schuld.",
  "Geen sprint nodig, een wandeling mag ook, zonder schuld.",
  "Vandaag telt mee, ook als het stil voelt, zonder schuld.",
  "Je bent waardevol, ook op een stille modus, zonder schuld.",
  "Rust hoort bij je systeem, niet alleen bij weekend, zonder schuld.",
  "Je brein vraagt om lucht, geef het die ruimte, zonder schuld.",
  "Eén ding met aandacht is meer dan genoeg, zonder schuld.",
  "Je mag nee zeggen tegen extra ballast vandaag, zonder schuld.",
  "Langzaam voelen is geen mislukking, zonder schuld.",
  "Vandaag mag je kiezen voor wat haalbaar voelt, zonder schuld.",
  "Je hoeft niet op te laden voor de hele week, alleen voor nu, zonder schuld.",
  "Een zachte start is ook een start, zonder schuld.",
  "Je energie is informatie, geen oordeel, zonder schuld.",
  "Minder prikkels vandaag is zelfzorg, zonder schuld.",
  "Je mag prioriteit geven aan wat rust geeft, zonder schuld.",
  "Het is oké als vandaag vooral over ademen gaat, zonder schuld.",
  "Rustig aan vandaag is een slimme keuze, dat telt mee.",
  "Je tempo mag vandaag zacht zijn, dat telt mee.",
  "Lage energie vraagt om zachte grenzen, dat telt mee.",
  "Kleine stappen zijn vandaag genoeg, dat telt mee.",
  "Je hoeft vandaag niet te bewijzen hoeveel je aankunt, dat telt mee.",
  "Een rustige dag is ook een goede dag, dat telt mee.",
  "Luister naar wat je lichaam vandaag fluistert, dat telt mee.",
  "Minder doen is soms de beste planning, dat telt mee.",
  "Je mag vandaag ruimte houden voor herstel, dat telt mee.",
  "Zachtheid naar jezelf is vandaag goud waard, dat telt mee.",
  "Geen sprint nodig, een wandeling mag ook, dat telt mee.",
  "Vandaag telt mee, ook als het stil voelt, dat telt mee.",
  "Je bent waardevol, ook op een stille modus, dat telt mee.",
  "Rust hoort bij je systeem, niet alleen bij weekend, dat telt mee.",
  "Je brein vraagt om lucht, geef het die ruimte, dat telt mee.",
  "Eén ding met aandacht is meer dan genoeg, dat telt mee.",
  "Je mag nee zeggen tegen extra ballast vandaag, dat telt mee.",
  "Langzaam voelen is geen mislukking, dat telt mee.",
  "Vandaag mag je kiezen voor wat haalbaar voelt, dat telt mee.",
  "Je hoeft niet op te laden voor de hele week, alleen voor nu, dat telt mee.",
  "Een zachte start is ook een start, dat telt mee.",
  "Je energie is informatie, geen oordeel, dat telt mee.",
  "Minder prikkels vandaag is zelfzorg, dat telt mee.",
  "Je mag prioriteit geven aan wat rust geeft, dat telt mee.",
  "Het is oké als vandaag vooral over ademen gaat, dat telt mee.",
  "Rustig aan vandaag is een slimme keuze, je mag dit tempo houden.",
  "Je tempo mag vandaag zacht zijn, je mag dit tempo houden.",
  "Lage energie vraagt om zachte grenzen, je mag dit tempo houden.",
  "Kleine stappen zijn vandaag genoeg, je mag dit tempo houden.",
  "Je hoeft vandaag niet te bewijzen hoeveel je aankunt, je mag dit tempo houden.",
  "Een rustige dag is ook een goede dag, je mag dit tempo houden.",
  "Luister naar wat je lichaam vandaag fluistert, je mag dit tempo houden.",
  "Minder doen is soms de beste planning, je mag dit tempo houden.",
  "Je mag vandaag ruimte houden voor herstel, je mag dit tempo houden.",
  "Zachtheid naar jezelf is vandaag goud waard, je mag dit tempo houden.",
  "Geen sprint nodig, een wandeling mag ook, je mag dit tempo houden.",
  "Vandaag telt mee, ook als het stil voelt, je mag dit tempo houden.",
  "Je bent waardevol, ook op een stille modus, je mag dit tempo houden.",
  "Rust hoort bij je systeem, niet alleen bij weekend, je mag dit tempo houden.",
  "Je brein vraagt om lucht, geef het die ruimte, je mag dit tempo houden.",
  "Eén ding met aandacht is meer dan genoeg, je mag dit tempo houden.",
  "Je mag nee zeggen tegen extra ballast vandaag, je mag dit tempo houden.",
  "Langzaam voelen is geen mislukking, je mag dit tempo houden.",
  "Vandaag mag je kiezen voor wat haalbaar voelt, je mag dit tempo houden.",
  "Je hoeft niet op te laden voor de hele week, alleen voor nu, je mag dit tempo houden.",
  "Een zachte start is ook een start, je mag dit tempo houden.",
  "Je energie is informatie, geen oordeel, je mag dit tempo houden.",
  "Minder prikkels vandaag is zelfzorg, je mag dit tempo houden.",
  "Je mag prioriteit geven aan wat rust geeft, je mag dit tempo houden.",
  "Het is oké als vandaag vooral over ademen gaat, je mag dit tempo houden.",
];

const MEDIUM_QUOTES: string[] = [
  "Lekker stabiel vandaag, hou het haalbaar.",
  "Je zit in een fijne middenstand, hou het haalbaar.",
  "Normale energie is een fijne basis, hou het haalbaar.",
  "Vandaag kun je rustig bouwen op wat past, hou het haalbaar.",
  "Balans vandaag betekent kiezen wat haalbaar is, hou het haalbaar.",
  "Je hoeft niet te kiezen tussen rust en actie, mix mag, hou het haalbaar.",
  "Een steady tempo is vaak het slimste tempo, hou het haalbaar.",
  "Vandaag mag je plannen zonder jezelf te overvragen, hou het haalbaar.",
  "Je energie voelt vandaag bruikbaar, hou het haalbaar.",
  "Een middenstand helpt je tempo duurzaam te houden, hou het haalbaar.",
  "Vandaag is een goede dag voor duidelijke keuzes, hou het haalbaar.",
  "Je mag vandaag bouwen op wat stabiel voelt, hou het haalbaar.",
  "Normale energie vraagt om realistische verwachtingen, hou het haalbaar.",
  "Eén focus per moment is vandaag genoeg, hou het haalbaar.",
  "Je tempo vandaag mag steady blijven, hou het haalbaar.",
  "Balans is vandaag genoeg doen met genoeg pauze, hou het haalbaar.",
  "Je zit goed genoeg om voorzichtig vooruit te gaan, hou het haalbaar.",
  "Vandaag kun je kiezen zonder extremes, hou het haalbaar.",
  "Je energie is vandaag bruikbaar, verdeel hem zacht, hou het haalbaar.",
  "Middenstand geeft ruimte om te plannen, hou het haalbaar.",
  "Je mag vandaag werken op een haalbaar tempo, hou het haalbaar.",
  "Vandaag kun je focussen op wat vandaag past, hou het haalbaar.",
  "Je mag vandaag plannen met mildheid naar jezelf, hou het haalbaar.",
  "Normale energie is een fijne basis voor structuur, hou het haalbaar.",
  "Vandaag kun je bouwen zonder jezelf te overvragen, hou het haalbaar.",
  "Lekker stabiel vandaag, dat is fijn.",
  "Je zit in een fijne middenstand, dat is fijn.",
  "Normale energie is een fijne basis, dat is fijn.",
  "Vandaag kun je rustig bouwen op wat past, dat is fijn.",
  "Balans vandaag betekent kiezen wat haalbaar is, dat is fijn.",
  "Je hoeft niet te kiezen tussen rust en actie, mix mag, dat is fijn.",
  "Een steady tempo is vaak het slimste tempo, dat is fijn.",
  "Vandaag mag je plannen zonder jezelf te overvragen, dat is fijn.",
  "Je energie voelt vandaag bruikbaar, dat is fijn.",
  "Een middenstand helpt je tempo duurzaam te houden, dat is fijn.",
  "Vandaag is een goede dag voor duidelijke keuzes, dat is fijn.",
  "Je mag vandaag bouwen op wat stabiel voelt, dat is fijn.",
  "Normale energie vraagt om realistische verwachtingen, dat is fijn.",
  "Eén focus per moment is vandaag genoeg, dat is fijn.",
  "Je tempo vandaag mag steady blijven, dat is fijn.",
  "Balans is vandaag genoeg doen met genoeg pauze, dat is fijn.",
  "Je zit goed genoeg om voorzichtig vooruit te gaan, dat is fijn.",
  "Vandaag kun je kiezen zonder extremes, dat is fijn.",
  "Je energie is vandaag bruikbaar, verdeel hem zacht, dat is fijn.",
  "Middenstand geeft ruimte om te plannen, dat is fijn.",
  "Je mag vandaag werken op een haalbaar tempo, dat is fijn.",
  "Vandaag kun je focussen op wat vandaag past, dat is fijn.",
  "Je mag vandaag plannen met mildheid naar jezelf, dat is fijn.",
  "Normale energie is een fijne basis voor structuur, dat is fijn.",
  "Vandaag kun je bouwen zonder jezelf te overvragen, dat is fijn.",
  "Lekker stabiel vandaag, geen haast nodig.",
  "Je zit in een fijne middenstand, geen haast nodig.",
  "Normale energie is een fijne basis, geen haast nodig.",
  "Vandaag kun je rustig bouwen op wat past, geen haast nodig.",
  "Balans vandaag betekent kiezen wat haalbaar is, geen haast nodig.",
  "Je hoeft niet te kiezen tussen rust en actie, mix mag, geen haast nodig.",
  "Een steady tempo is vaak het slimste tempo, geen haast nodig.",
  "Vandaag mag je plannen zonder jezelf te overvragen, geen haast nodig.",
  "Je energie voelt vandaag bruikbaar, geen haast nodig.",
  "Een middenstand helpt je tempo duurzaam te houden, geen haast nodig.",
  "Vandaag is een goede dag voor duidelijke keuzes, geen haast nodig.",
  "Je mag vandaag bouwen op wat stabiel voelt, geen haast nodig.",
  "Normale energie vraagt om realistische verwachtingen, geen haast nodig.",
  "Eén focus per moment is vandaag genoeg, geen haast nodig.",
  "Je tempo vandaag mag steady blijven, geen haast nodig.",
  "Balans is vandaag genoeg doen met genoeg pauze, geen haast nodig.",
  "Je zit goed genoeg om voorzichtig vooruit te gaan, geen haast nodig.",
  "Vandaag kun je kiezen zonder extremes, geen haast nodig.",
  "Je energie is vandaag bruikbaar, verdeel hem zacht, geen haast nodig.",
  "Middenstand geeft ruimte om te plannen, geen haast nodig.",
  "Je mag vandaag werken op een haalbaar tempo, geen haast nodig.",
  "Vandaag kun je focussen op wat vandaag past, geen haast nodig.",
  "Je mag vandaag plannen met mildheid naar jezelf, geen haast nodig.",
  "Normale energie is een fijne basis voor structuur, geen haast nodig.",
  "Vandaag kun je bouwen zonder jezelf te overvragen, geen haast nodig.",
  "Lekker stabiel vandaag, kies met zorg.",
  "Je zit in een fijne middenstand, kies met zorg.",
  "Normale energie is een fijne basis, kies met zorg.",
  "Vandaag kun je rustig bouwen op wat past, kies met zorg.",
  "Balans vandaag betekent kiezen wat haalbaar is, kies met zorg.",
  "Je hoeft niet te kiezen tussen rust en actie, mix mag, kies met zorg.",
  "Een steady tempo is vaak het slimste tempo, kies met zorg.",
  "Vandaag mag je plannen zonder jezelf te overvragen, kies met zorg.",
  "Je energie voelt vandaag bruikbaar, kies met zorg.",
  "Een middenstand helpt je tempo duurzaam te houden, kies met zorg.",
  "Vandaag is een goede dag voor duidelijke keuzes, kies met zorg.",
  "Je mag vandaag bouwen op wat stabiel voelt, kies met zorg.",
  "Normale energie vraagt om realistische verwachtingen, kies met zorg.",
  "Eén focus per moment is vandaag genoeg, kies met zorg.",
  "Je tempo vandaag mag steady blijven, kies met zorg.",
  "Balans is vandaag genoeg doen met genoeg pauze, kies met zorg.",
  "Je zit goed genoeg om voorzichtig vooruit te gaan, kies met zorg.",
  "Vandaag kun je kiezen zonder extremes, kies met zorg.",
  "Je energie is vandaag bruikbaar, verdeel hem zacht, kies met zorg.",
  "Middenstand geeft ruimte om te plannen, kies met zorg.",
  "Je mag vandaag werken op een haalbaar tempo, kies met zorg.",
  "Vandaag kun je focussen op wat vandaag past, kies met zorg.",
  "Je mag vandaag plannen met mildheid naar jezelf, kies met zorg.",
  "Normale energie is een fijne basis voor structuur, kies met zorg.",
  "Vandaag kun je bouwen zonder jezelf te overvragen, kies met zorg.",
];

const HIGH_QUOTES: string[] = [
  "Je hebt vandaag extra ruimte om voorzichtig vooruit te gaan, dat is fijn.",
  "Vandaag voelt je energie helder genoeg om rustig te kiezen, dat is fijn.",
  "Met deze energie mag je mild genieten van vooruitgang, dat is fijn.",
  "Je zit vandaag lekker in je vel om kleine stappen te zetten, dat is fijn.",
  "Je brein heeft vandaag ruimte om helder te kiezen, dat is fijn.",
  "Vandaag kun je met lichtheid verder bouwen, dat is fijn.",
  "Je mag vandaag voorzichtig genieten van je eigen tempo, dat is fijn.",
  "Je energie nodigt uit om rustig te versnellen waar het goed voelt, dat is fijn.",
  "Vandaag is een fijne dag om je focus te geven aan wat past, dat is fijn.",
  "Je mag vandaag rustig bouwen aan wat energie geeft, dat is fijn.",
  "Je hebt vandaag pit om zacht vooruit te gaan, dat is fijn.",
  "Vandaag kun je spelen met een goed tempo zonder overdrijven, dat is fijn.",
  "Je mag vandaag kalm vooruit met je eerste stap, dat is fijn.",
  "Je energie geeft ruimte om te kiezen voor wat haalbaar is, dat is fijn.",
  "Vandaag kun je zacht vooruit met je planning, dat is fijn.",
  "Je mag vandaag kiezen voor wat vandaag haalbaar voelt, dat is fijn.",
  "Je zit goed genoeg om vandaag voorzichtig te plannen, dat is fijn.",
  "Vandaag kun je met plezier kleine stappen zetten, dat is fijn.",
  "Je mag vandaag voorzichtig gas geven op wat goed voelt, dat is fijn.",
  "Je energie is vandaag een fijne motor voor je focus, dat is fijn.",
  "Vandaag kun je met mildheid je dag vorm geven, dat is fijn.",
  "Je mag vandaag bouwen aan rust en vooruitgang, dat is fijn.",
  "Je hebt vandaag vaart om rustig te kiezen voor je focus, dat is fijn.",
  "Vandaag kun je rustig versnellen op wat je energie draagt, dat is fijn.",
  "Je mag vandaag vooruit zonder haast op je eigen tempo, dat is fijn.",
  "Je hebt vandaag extra ruimte om voorzichtig vooruit te gaan, zonder druk.",
  "Vandaag voelt je energie helder genoeg om rustig te kiezen, zonder druk.",
  "Met deze energie mag je mild genieten van vooruitgang, zonder druk.",
  "Je zit vandaag lekker in je vel om kleine stappen te zetten, zonder druk.",
  "Je brein heeft vandaag ruimte om helder te kiezen, zonder druk.",
  "Vandaag kun je met lichtheid verder bouwen, zonder druk.",
  "Je mag vandaag voorzichtig genieten van je eigen tempo, zonder druk.",
  "Je energie nodigt uit om rustig te versnellen waar het goed voelt, zonder druk.",
  "Vandaag is een fijne dag om je focus te geven aan wat past, zonder druk.",
  "Je mag vandaag rustig bouwen aan wat energie geeft, zonder druk.",
  "Je hebt vandaag pit om zacht vooruit te gaan, zonder druk.",
  "Vandaag kun je spelen met een goed tempo zonder overdrijven, zonder druk.",
  "Je mag vandaag kalm vooruit met je eerste stap, zonder druk.",
  "Je energie geeft ruimte om te kiezen voor wat haalbaar is, zonder druk.",
  "Vandaag kun je zacht vooruit met je planning, zonder druk.",
  "Je mag vandaag kiezen voor wat vandaag haalbaar voelt, zonder druk.",
  "Je zit goed genoeg om vandaag voorzichtig te plannen, zonder druk.",
  "Vandaag kun je met plezier kleine stappen zetten, zonder druk.",
  "Je mag vandaag voorzichtig gas geven op wat goed voelt, zonder druk.",
  "Je energie is vandaag een fijne motor voor je focus, zonder druk.",
  "Vandaag kun je met mildheid je dag vorm geven, zonder druk.",
  "Je mag vandaag bouwen aan rust en vooruitgang, zonder druk.",
  "Je hebt vandaag vaart om rustig te kiezen voor je focus, zonder druk.",
  "Vandaag kun je rustig versnellen op wat je energie draagt, zonder druk.",
  "Je mag vandaag vooruit zonder haast op je eigen tempo, zonder druk.",
  "Je hebt vandaag extra ruimte om voorzichtig vooruit te gaan, met mildheid.",
  "Vandaag voelt je energie helder genoeg om rustig te kiezen, met mildheid.",
  "Met deze energie mag je mild genieten van vooruitgang, met mildheid.",
  "Je zit vandaag lekker in je vel om kleine stappen te zetten, met mildheid.",
  "Je brein heeft vandaag ruimte om helder te kiezen, met mildheid.",
  "Vandaag kun je met lichtheid verder bouwen, met mildheid.",
  "Je mag vandaag voorzichtig genieten van je eigen tempo, met mildheid.",
  "Je energie nodigt uit om rustig te versnellen waar het goed voelt, met mildheid.",
  "Vandaag is een fijne dag om je focus te geven aan wat past, met mildheid.",
  "Je mag vandaag rustig bouwen aan wat energie geeft, met mildheid.",
  "Je hebt vandaag pit om zacht vooruit te gaan, met mildheid.",
  "Vandaag kun je spelen met een goed tempo zonder overdrijven, met mildheid.",
  "Je mag vandaag kalm vooruit met je eerste stap, met mildheid.",
  "Je energie geeft ruimte om te kiezen voor wat haalbaar is, met mildheid.",
  "Vandaag kun je zacht vooruit met je planning, met mildheid.",
  "Je mag vandaag kiezen voor wat vandaag haalbaar voelt, met mildheid.",
  "Je zit goed genoeg om vandaag voorzichtig te plannen, met mildheid.",
  "Vandaag kun je met plezier kleine stappen zetten, met mildheid.",
  "Je mag vandaag voorzichtig gas geven op wat goed voelt, met mildheid.",
  "Je energie is vandaag een fijne motor voor je focus, met mildheid.",
  "Vandaag kun je met mildheid je dag vorm geven, met mildheid.",
  "Je mag vandaag bouwen aan rust en vooruitgang, met mildheid.",
  "Je hebt vandaag vaart om rustig te kiezen voor je focus, met mildheid.",
  "Vandaag kun je rustig versnellen op wat je energie draagt, met mildheid.",
  "Je mag vandaag vooruit zonder haast op je eigen tempo, met mildheid.",
  "Je hebt vandaag extra ruimte om voorzichtig vooruit te gaan, je mag trots zijn op jezelf.",
  "Vandaag voelt je energie helder genoeg om rustig te kiezen, je mag trots zijn op jezelf.",
  "Met deze energie mag je mild genieten van vooruitgang, je mag trots zijn op jezelf.",
  "Je zit vandaag lekker in je vel om kleine stappen te zetten, je mag trots zijn op jezelf.",
  "Je brein heeft vandaag ruimte om helder te kiezen, je mag trots zijn op jezelf.",
  "Vandaag kun je met lichtheid verder bouwen, je mag trots zijn op jezelf.",
  "Je mag vandaag voorzichtig genieten van je eigen tempo, je mag trots zijn op jezelf.",
  "Je energie nodigt uit om rustig te versnellen waar het goed voelt, je mag trots zijn op jezelf.",
  "Vandaag is een fijne dag om je focus te geven aan wat past, je mag trots zijn op jezelf.",
  "Je mag vandaag rustig bouwen aan wat energie geeft, je mag trots zijn op jezelf.",
  "Je hebt vandaag pit om zacht vooruit te gaan, je mag trots zijn op jezelf.",
  "Vandaag kun je spelen met een goed tempo zonder overdrijven, je mag trots zijn op jezelf.",
  "Je mag vandaag kalm vooruit met je eerste stap, je mag trots zijn op jezelf.",
  "Je energie geeft ruimte om te kiezen voor wat haalbaar is, je mag trots zijn op jezelf.",
  "Vandaag kun je zacht vooruit met je planning, je mag trots zijn op jezelf.",
  "Je mag vandaag kiezen voor wat vandaag haalbaar voelt, je mag trots zijn op jezelf.",
  "Je zit goed genoeg om vandaag voorzichtig te plannen, je mag trots zijn op jezelf.",
  "Vandaag kun je met plezier kleine stappen zetten, je mag trots zijn op jezelf.",
  "Je mag vandaag voorzichtig gas geven op wat goed voelt, je mag trots zijn op jezelf.",
  "Je energie is vandaag een fijne motor voor je focus, je mag trots zijn op jezelf.",
  "Vandaag kun je met mildheid je dag vorm geven, je mag trots zijn op jezelf.",
  "Je mag vandaag bouwen aan rust en vooruitgang, je mag trots zijn op jezelf.",
  "Je hebt vandaag vaart om rustig te kiezen voor je focus, je mag trots zijn op jezelf.",
  "Vandaag kun je rustig versnellen op wat je energie draagt, je mag trots zijn op jezelf.",
  "Je mag vandaag vooruit zonder haast op je eigen tempo, je mag trots zijn op jezelf.",
];

const LISTS: Record<EnergyDoneLevel, readonly string[]> = {
  low: LOW_QUOTES,
  medium: MEDIUM_QUOTES,
  high: HIGH_QUOTES,
};

function assertLength(name: string, list: readonly string[], n: number) {
  if (list.length !== n) throw new Error(`${name}: verwacht ${n} regels, got ${list.length}`);
}
assertLength("LOW_QUOTES", LOW_QUOTES, 100);
assertLength("MEDIUM_QUOTES", MEDIUM_QUOTES, 100);
assertLength("HIGH_QUOTES", HIGH_QUOTES, 100);

const SESSION_PICK_KEY = "structuro_energy_done_pick";

/** Volgende compliment of tip voor dit energieniveau; roteert per level via localStorage. */
export function getNextEnergyDoneMessage(level: EnergyDoneLevel): string {
  const list = LISTS[level];
  const key = KEYS[level];
  let idx = 0;
  try {
    const raw = typeof window !== "undefined" ? window.localStorage.getItem(key) : null;
    if (raw) idx = parseInt(raw, 10) || 0;
  } catch { /* ignore */ }
  const safe = ((idx % list.length) + list.length) % list.length;
  const text = list[safe] ?? list[0];
  try {
    if (typeof window !== "undefined") window.localStorage.setItem(key, String(idx + 1));
  } catch { /* ignore */ }
  return text;
}

/**
 * Zelfde bericht binnen één sessie en energieniveau (handig bij React Strict Mode),
 * maar wel een nieuwe rotatie als het niveau of de dag verandert.
 */
export function getStableEnergyDoneMessage(level: EnergyDoneLevel): string {
  const day = new Date().toISOString().slice(0, 10);
  try {
    const raw = typeof window !== "undefined" ? window.sessionStorage.getItem(SESSION_PICK_KEY) : null;
    if (raw) {
      const parsed = JSON.parse(raw) as { day: string; level: EnergyDoneLevel; text: string };
      if (parsed.day === day && parsed.level === level && typeof parsed.text === "string") {
        return parsed.text;
      }
    }
  } catch { /* ignore */ }
  const text = getNextEnergyDoneMessage(level);
  try {
    if (typeof window !== "undefined") {
      window.sessionStorage.setItem(SESSION_PICK_KEY, JSON.stringify({ day, level, text }));
    }
  } catch { /* ignore */ }
  return text;
}