import type { Locale } from "@/lib/i18n/types";

export const V2_DONE_QUOTE_INDEX_KEY = "v2_done_quote_index";

/** Korte, prikkelarme zinnen over afronden met een ADHD-brein. Geen streak, geen score. */
export const V2_DONE_QUOTES_NL: readonly string[] = [
  "Af is een signaal naar je brein: dit mag uit je hoofd.",
  "Een open lus is dicht. Dat geeft rust, niet een score.",
  "Je ADHD-brein onthoudt open dingen extra hard. Dit één ding is klaar.",
  "Klaar zijn is bewijs dat starten mogelijk was.",
  "Je werkgeheugen heeft één ding minder te dragen.",
  "Afronden geeft een korte, echte beloning. Dat mag je voelen.",
  "Het hoeft niet groter. Dit was genoeg voor nu.",
  "Je koos, je deed, je sloot af. Dat is zeldzaam fijn.",
  "Minder ruis. Eén taak is van de stapel.",
  "Je lijst is lichter. Jij ook, een beetje.",
  "Dit telt omdat het af is, niet omdat het indrukwekkend was.",
  "Je brein mag stoppen met herinneren. Het is gedaan.",
  "Volgen-door was er. Eén keer is al veel.",
  "Geen ‘ik moet nog’. Dit hoeft niet meer.",
  "Afronden is een vorm van zorg voor jezelf.",
  "Je gaf je aandacht een einde. Dat is vriendelijk.",
  "Het onafgemaakte gevoel mag hier stoppen.",
  "Eén dichte deur in je hoofd. Meer lucht.",
  "Je deed het niet perfect. Je deed het af. Dat is de winst.",
  "Dit is bewijs tegen het verhaal dat niets lukt.",
  "Kleine afronding, grote stilte in je hoofd.",
  "Je externe geheugen werkte. Jij hoefde het niet alleen te onthouden.",
  "Klaar is een gevoel, geen cijfer.",
  "Je ADHD zoekt nieuw. Jij koos afmaken. Dat is moedig rustig.",
  "De taak mag je loslaten. Echt.",
  "Je hebt een einde gezet. Einden zijn zeldzaam en fijn.",
  "Minder open loops. Meer ruimte om niks te hoeven.",
  "Dit was moeilijk om te beginnen. Beginnen is nu voorbij.",
  "Je lichaam mag merken: het is klaar.",
  "Afronden is dopamine zonder circus.",
  "Je bent iemand die dit afkreeg. Vandaag, hier.",
  "Het mag saai voelen. Saai af is nog steeds af.",
  "Je hoofd hoeft dit niet te herhalen vannacht.",
  "Eén ding minder dat aan je trekt.",
  "Je gaf een taak een einde. Dat is structuur.",
  "Niet meer, niet minder. Dit is rond.",
  "Je aandacht had een landingsplek. En is geland.",
  "Het vinkje is geen oordeel. Het is een feit.",
  "Je mocht stoppen. Stoppen was de opdracht.",
  "Dit telt voor een brein dat snel verder wil.",
  "Je hebt bewijs. Niet een pep-talk.",
  "De dag is al geslaagd in dit ene ding.",
  "Afronden maakt morgen stiller, een tikje.",
  "Je koos afronden boven eindeloos openlaten.",
  "Het mag voelen alsof het niks was. Het was wél af.",
  "Je werkte tegen uitstel, niet tegen jezelf.",
  "Een taak uit je hoofd is een vorm van ademhalen.",
  "Je hebt de lus gesloten. Dat is Structuro.",
  "Geen extra ronde nodig. Dit mag klaar blijven.",
  "Je ADHD onthoudt wat blijft liggen. Dit blijft niet liggen.",
  "Klaar zijn is ook een skill. Je oefende die net.",
  "Je gaf jezelf een einde in plaats van nóg een start.",
  "Dit is genoeg om op te staan en weg te lopen.",
  "Minder schuld over ‘niet afgemaakt’. Dit wél.",
  "Je aandacht kreeg een slotakkoord.",
  "Het open tabblad in je hoofd is dicht.",
  "Je deed het in jouw tempo. En het is af.",
  "Afronden zegt: ik ben te vertrouwen voor dit ding.",
  "Niet alles hoeft af. Dit wél, en dat is fijn.",
  "Je mag dit vieren zonder confetti.",
  "Een einde is een cadeau aan je zenuwstelsel.",
  "Je hebt minder te onthouden dan een minuut geleden.",
  "Dit was een keuze. Keuzes die landen, kalmeren.",
  "Je ging tot het einde van dit kleine stuk.",
  "Het mag klaar zijn zonder dat de wereld verandert.",
  "Je gaf een taak rust. Jij krijgt die rust terug.",
  "Geen half werk in je achterhoofd. Dit is heel.",
  "Afronden is vriendelijk voor morgen-jij.",
  "Je hebt een feit: dit hoeft niet opnieuw.",
  "Het zware deel was vaak beginnen. Dat is voorbij.",
  "Je brein mag schakelen naar niks, even.",
  "Dit is geen streak. Dit is één eerlijk einde.",
  "Je hebt iets uit de mist gehaald en neergezet.",
  "Klaar mag licht aanvoelen. Licht is oké.",
  "Je hebt de opdracht ingelost die je jezelf gaf.",
  "Minder ‘later’. Meer nu, af.",
  "Je ADHD houdt van nieuw. Afronden is een andere beloning.",
  "Dit telt ook als niemand het zag.",
  "Je hebt een stukje chaos een rand gegeven.",
  "Het mag stoppen. Echt stoppen.",
  "Je werkte met je brein, niet tegen de klok.",
  "Eén dichte taak is meer dan tien open voornemens.",
  "Je hebt bewijs dat afronden bestaat, ook voor jou.",
  "Dit is een zacht succes. Zacht is sterk genoeg.",
  "Je mag verder zonder dit mee te torsen.",
  "Afronden maakt ruimte. Geen druk om die te vullen.",
  "Je hebt een einde waar je op kunt leunen.",
  "Het vinkje zegt niks over je waarde. Alleen: gedaan.",
  "Je gaf aandacht, en daarna rust.",
  "Dit mag in je archief. Niet in je piekerlijst.",
  "Je koos afronden. Dat is een vorm van vriendschap met jezelf.",
  "Een taak minder die om aandacht schreeuwt.",
  "Je hebt vandaag al een lus gesloten.",
  "Het is af, dus je mag wegkijken.",
  "Geen extra bewijs nodig. Dit was het bewijs.",
  "Je hoofd is een tik stiller. Dat is de winst.",
  "Afronden is geen prestatiecultuur. Het is afronden.",
  "Je hebt dit uit je werkgeheugen gezet. Fijn zo.",
  "Dit einde is van jou. Niemand hoeft het te keuren.",
  "Klaar. Dat mag het laatste woord zijn.",
];

export const V2_DONE_QUOTES_EN: readonly string[] = [
  "Done is a signal to your brain: this can leave your head.",
  "An open loop is closed. That brings calm, not a score.",
  "Your ADHD brain holds open things extra tight. This one thing is finished.",
  "Finishing is proof that starting was possible.",
  "Your working memory has one less thing to carry.",
  "Completing gives a short, real reward. You can feel that.",
  "It does not have to be bigger. This was enough for now.",
  "You chose, you did, you closed it. That is quietly rare.",
  "Less noise. One task is off the pile.",
  "Your list is lighter. You are too, a little.",
  "This counts because it is done, not because it was impressive.",
  "Your brain can stop reminding you. It is finished.",
  "Follow-through showed up. Once is already a lot.",
  "No more ‘I still have to’. This does not need you.",
  "Finishing is a form of care for yourself.",
  "You gave your attention an ending. That is kind.",
  "The unfinished feeling can stop here.",
  "One closed door in your head. More air.",
  "You did not do it perfectly. You did it. That is the win.",
  "This is evidence against the story that nothing works.",
  "Small finish, big quiet in your head.",
  "Your external memory worked. You did not have to hold it alone.",
  "Done is a feeling, not a number.",
  "Your ADHD looks for new. You chose finish. That is bravely calm.",
  "The task can let you go. Really.",
  "You put an ending on it. Endings are rare and kind.",
  "Fewer open loops. More room to need nothing.",
  "Starting was the hard part. Starting is over.",
  "Your body can notice: it is finished.",
  "Completing is dopamine without a circus.",
  "You are someone who finished this. Today, here.",
  "It may feel boring. Boring-done is still done.",
  "Your head does not have to repeat this tonight.",
  "One less thing pulling at you.",
  "You gave a task an ending. That is structure.",
  "Not more, not less. This is complete.",
  "Your attention had a landing place. And it landed.",
  "The check is not a verdict. It is a fact.",
  "You were allowed to stop. Stopping was the job.",
  "This counts for a brain that wants to move on fast.",
  "You have proof. Not a pep talk.",
  "The day already succeeded in this one thing.",
  "Finishing makes tomorrow a little quieter.",
  "You chose closing over leaving it open forever.",
  "It may feel like nothing. It was still done.",
  "You worked against delay, not against yourself.",
  "A task out of your head is a kind of breathing.",
  "You closed the loop. That is Structuro.",
  "No extra round needed. This can stay finished.",
  "Your ADHD remembers what stays open. This does not stay open.",
  "Finishing is also a skill. You just practised it.",
  "You gave yourself an ending instead of another start.",
  "This is enough to stand up and walk away.",
  "Less guilt about ‘not finished’. This one was.",
  "Your attention got a closing note.",
  "The open tab in your head is closed.",
  "You did it at your pace. And it is done.",
  "Finishing says: I can be trusted with this one thing.",
  "Not everything needs to be done. This did, and that is good.",
  "You may mark this without confetti.",
  "An ending is a gift to your nervous system.",
  "You have less to remember than a minute ago.",
  "This was a choice. Choices that land, calm you.",
  "You went to the end of this small piece.",
  "It can be done without the world changing.",
  "You gave a task rest. You get that rest back.",
  "No half-work in the back of your mind. This is whole.",
  "Finishing is kind to tomorrow-you.",
  "You have a fact: this does not need doing again.",
  "The heavy part was often starting. That is over.",
  "Your brain may switch to nothing, for a bit.",
  "This is not a streak. This is one honest ending.",
  "You pulled something out of the fog and set it down.",
  "Done may feel light. Light is okay.",
  "You kept the promise you made to yourself.",
  "Less ‘later’. More now, finished.",
  "Your ADHD loves new. Finishing is a different reward.",
  "This counts even if nobody saw it.",
  "You gave a piece of chaos an edge.",
  "It can stop. Really stop.",
  "You worked with your brain, not against the clock.",
  "One closed task beats ten open intentions.",
  "You have proof that finishing exists, also for you.",
  "This is a quiet success. Quiet is strong enough.",
  "You can go on without carrying this.",
  "Finishing makes space. No pressure to fill it.",
  "You have an ending you can lean on.",
  "The check says nothing about your worth. Only: done.",
  "You gave attention, and then rest.",
  "This can go in the archive. Not in the worry list.",
  "You chose finishing. That is a friendship with yourself.",
  "One less task shouting for attention.",
  "You already closed a loop today.",
  "It is done, so you may look away.",
  "No extra proof needed. This was the proof.",
  "Your head is a touch quieter. That is the win.",
  "Finishing is not hustle culture. It is finishing.",
  "You took this out of working memory. Good.",
  "This ending is yours. Nobody has to grade it.",
  "Done. That may be the last word.",
];

export function pickV2DoneQuote(locale: Locale, index: number): string {
  const list = locale === "en" ? V2_DONE_QUOTES_EN : V2_DONE_QUOTES_NL;
  const i = ((index % list.length) + list.length) % list.length;
  return list[i] ?? list[0];
}

export function takeNextV2DoneQuote(locale: Locale): string {
  let index = 0;
  if (typeof window !== "undefined") {
    try {
      const raw = window.localStorage.getItem(V2_DONE_QUOTE_INDEX_KEY);
      const n = Number(raw);
      if (Number.isFinite(n) && n >= 0) index = Math.floor(n);
    } catch {
      /* privémodus */
    }
  }
  const quote = pickV2DoneQuote(locale, index);
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(V2_DONE_QUOTE_INDEX_KEY, String(index + 1));
    } catch {
      /* privémodus */
    }
  }
  return quote;
}
