import type { Locale } from "@/lib/i18n/types";

export const V2_DONE_QUOTE_INDEX_KEY = "v2_done_quote_index";

/** Korte, prikkelarme zinnen over afronden met een ADHD-brein. Geen streak, geen score. */
export const V2_DONE_QUOTES_NL: readonly string[] = [
  "Af is een signaal naar je brein: dit mag uit je hoofd.",
  "Een open lus is dicht. Dat geeft rust, niet een score.",
  "Je ADHD-brein onthoudt open dingen extra hard. Dit één ding is klaar.",
  "Klaar zijn is bewijs dat starten mogelijk was.",
  "Je werkgeheugen heeft één ding minder te dragen.",
  "Afronden geeft een korte, echte beloning. Dat mag je voelen.",
  "Het hoeft niet groter. Dit was genoeg voor nu.",
  "Je koos, je deed, je sloot af. Dat is zeldzaam fijn.",
  "Minder ruis. Eén taak is van de stapel.",
  "Je lijst is lichter. Jij ook, een beetje.",
  "Dit telt omdat het af is, niet omdat het indrukwekkend was.",
  "Je brein mag stoppen met herinneren. Het is gedaan.",
  "Volgen-door was er. Eén keer is al veel.",
  "Geen ‘ik moet nog’. Dit hoeft niet meer.",
  "Afronden is een vorm van zorg voor jezelf.",
  "Je gaf je aandacht een einde. Dat is vriendelijk.",
  "Het onafgemaakte gevoel mag hier stoppen.",
  "Eén dichte deur in je hoofd. Meer lucht.",
  "Je deed het niet perfect. Je deed het af. Dat is de winst.",
  "Dit is bewijs tegen het verhaal dat niets lukt.",
  "Kleine afronding, grote stilte in je hoofd.",
  "Je externe geheugen werkte. Jij hoefde het niet alleen te onthouden.",
  "Klaar is een gevoel, geen cijfer.",
  "Je ADHD zoekt nieuw. Jij koos afmaken. Dat is moedig rustig.",
  "De taak mag je loslaten. Echt.",
  "Je hebt een einde gezet. Einden zijn zeldzaam en fijn.",
  "Minder open loops. Meer ruimte om niks te hoeven.",
  "Dit was moeilijk om te beginnen. Beginnen is nu voorbij.",
  "Je lichaam mag merken: het is klaar.",
  "Afronden is dopamine zonder circus.",
  "Je bent iemand die dit afkreeg. Vandaag, hier.",
  "Het mag saai voelen. Saai af is nog steeds af.",
  "Je hoofd hoeft dit niet te herhalen vannacht.",
  "Eén ding minder dat aan je trekt.",
  "Je gaf een taak een einde. Dat is structuur.",
  "Niet meer, niet minder. Dit is rond.",
  "Je aandacht had een landingsplek. En is geland.",
  "Het vinkje is geen oordeel. Het is een feit.",
  "Je mocht stoppen. Stoppen was de opdracht.",
  "Dit telt voor een brein dat snel verder wil.",
  "Je hebt bewijs. Niet een pep-talk.",
  "De dag is al geslaagd in dit ene ding.",
  "Afronden maakt morgen stiller, een tikje.",
  "Je koos afronden boven eindeloos openlaten.",
  "Het mag voelen alsof het niks was. Het was wél af.",
  "Je werkte tegen uitstel, niet tegen jezelf.",
  "Een taak uit je hoofd is een vorm van ademhalen.",
  "Je hebt de lus gesloten. Dat is Structuro.",
  "Geen extra ronde nodig. Dit mag klaar blijven.",
  "Je ADHD onthoudt wat blijft liggen. Dit blijft niet liggen.",
  "Klaar zijn is ook een skill. Je oefende die net.",
  "Je gaf jezelf een einde in plaats van nóg een start.",
  "Dit is genoeg om op te staan en weg te lopen.",
  "Minder schuld over ‘niet afgemaakt’. Dit wél.",
  "Je aandacht kreeg een slotakkoord.",
  "Het open tabblad in je hoofd is dicht.",
  "Je deed het in jouw tempo. En het is af.",
  "Afronden zegt: ik ben te vertrouwen voor dit ding.",
  "Niet alles hoeft af. Dit wél, en dat is fijn.",
  "Je mag dit vieren zonder confetti.",
  "Een einde is een cadeau aan je zenuwstelsel.",
  "Je hebt minder te onthouden dan een minuut geleden.",
  "Dit was een keuze. Keuzes die landen, kalmeren.",
  "Je ging tot het einde van dit kleine stuk.",
  "Het mag klaar zijn zonder dat de wereld verandert.",
  "Je gaf een taak rust. Jij krijgt die rust terug.",
  "Geen half werk in je achterhoofd. Dit is heel.",
  "Afronden is vriendelijk voor morgen-jij.",
  "Je hebt een feit: dit hoeft niet opnieuw.",
  "Het zware deel was vaak beginnen. Dat is voorbij.",
  "Je brein mag schakelen naar niks, even.",
  "Dit is geen streak. Dit is één eerlijk einde.",
  "Je hebt iets uit de mist gehaald en neergezet.",
  "Klaar mag licht aanvoelen. Licht is oké.",
  "Je hebt de opdracht ingelost die je jezelf gaf.",
  "Minder ‘later’. Meer nu, af.",
  "Je ADHD houdt van nieuw. Afronden is een andere beloning.",
  "Dit telt ook als niemand het zag.",
  "Je hebt een stukje chaos een rand gegeven.",
  "Het mag stoppen. Echt stoppen.",
  "Je werkte met je brein, niet tegen de klok.",
  "Eén dichte taak is meer dan tien open voornemens.",
  "Je hebt bewijs dat afronden bestaat, ook voor jou.",
  "Dit is een zacht succes. Zacht is sterk genoeg.",
  "Je mag verder zonder dit mee te torsen.",
  "Afronden maakt ruimte. Geen druk om die te vullen.",
  "Je hebt een einde waar je op kunt leunen.",
  "Het vinkje zegt niks over je waarde. Alleen: gedaan.",
  "Je gaf aandacht, en daarna rust.",
  "Dit mag in je archief. Niet in je piekerlijst.",
  "Je koos afronden. Dat is een vorm van vriendschap met jezelf.",
  "Een taak minder die om aandacht schreeuwt.",
  "Je hebt vandaag al een lus gesloten.",
  "Het is af, dus je mag wegkijken.",
  "Geen extra bewijs nodig. Dit was het bewijs.",
  "Je hoofd is een tik stiller. Dat is de winst.",
  "Afronden is geen prestatiecultuur. Het is afronden.",
  "Je hebt dit uit je werkgeheugen gezet. Fijn zo.",
  "Dit einde is van jou. Niemand hoeft het te keuren.",
  "Klaar. Dat mag het laatste woord zijn.",
  "Je gaf dit ding een einde. Dat is zorgvuldig.",
  "Aandacht die landt, is al een compliment.",
  "Je bleef tot het klaar was. Kort, en echt.",
  "Dit is volgen-door, zonder vuurwerk.",
  "Je hoofd mag dit dossier sluiten.",
  "Eén taak af. Geen extra verhaal erbij.",
  "Je koos afronden. Dat mag je horen.",
  "Het vinkje is vriendelijk, niet luid.",
  "Je hebt dit uit de wacht gehaald.",
  "Klaar zijn mag stil zijn. Stil is helder.",
  "Je kwam terug bij wat je beloofde.",
  "Dit was genoeg doen voor dit moment.",
  "Je liet de taak niet half open.",
  "Afronden is een zachte vorm van trouw.",
  "Je aandacht had een slot. Dat slot viel.",
  "Minder open eindes. Dat voelt schoner.",
  "Je deed het af, ook zonder zin.",
  "Dit telt in een brein dat snel afhaakt.",
  "Je gaf chaos een laatste punt.",
  "Het mag klaar zijn. Je mag dat geloven.",
  "Je hebt vandaag al iets neergelegd.",
  "Eén einde is een anker, geen podium.",
  "Je werkte door het lastige begin heen.",
  "Dit is bewijs dat stoppen ook lukt.",
  "Je lijst kreeg rust. Jij ook.",
  "Afronden zonder show. Precies goed.",
  "Je hebt dit ding niet laten zweven.",
  "Wat open stond, staat nu dicht.",
  "Je koos einde boven nog een begin.",
  "Dit mag bij de geweest-dingen.",
  "Je brein krijgt een korte, echte pauze.",
  "Klaar. Geen naschrift nodig.",
  "Je hield de draad vast tot hij af was.",
  "Dit is zorg voor je toekomstige zelf.",
  "Je hebt een kleine belofte ingelost.",
  "Dit zwijgt nu. Het trekt niet meer.",
  "Je gaf jezelf een zachte landing.",
  "Het mag voelen als niks bijzonders. Het is wél gedaan.",
  "Je ADHD wilde door. Jij bleef tot hier.",
  "Eén dichte lus. Adem maar.",
  "Je tilde dit uit de mist en zette het weg.",
  "Afronden is niet streng. Het is duidelijk.",
  "Je mag dit loslaten zonder schuld.",
  "Start tot stop: een volledige beweging.",
  "Je hoofd hoeft dit niet te bewaren.",
  "Klaar zijn is een vorm van vriendelijkheid.",
  "Je zette een punt waar uitstel een komma zette.",
  "Vijf minuten telt hetzelfde als vijftig, als het af is.",
  "Je hebt de taak tot de rand gebracht.",
  "Minder ruis achter je ogen.",
  "Je deed wat je nu kon. En sloot het.",
  "Dit is geen race. Dit is een einde.",
  "Je gaf aandacht, daarna een grens.",
  "Het vinkje is een feit, geen ster.",
  "Je kwam tot afronden. Dat is zeldzaam kalm.",
  "Dit mag je even geruststellen.",
  "Minder open tabbladen in je dag.",
  "De kamer in je hoofd is een tik groter.",
  "Je liet dit niet in de wachtkamer.",
  "Dit was genoeg om te stoppen.",
  "Je hebt een klein contract nagekomen.",
  "Klaar. De rest mag wachten.",
  "Je aandacht is weer van jou.",
  "Dit einde is licht, en dat is de bedoeling.",
  "Je werkte met wat er was. Het is af.",
  "Minder straks. Meer net gedaan.",
  "Je gaf je zenuwstelsel een duidelijk signaal.",
  "Dit telt omdat jij het afrondde.",
  "Je mag nu iets anders, of niets.",
  "Hier stopt het open gevoel.",
  "Je hebt dit ding netjes neergezet.",
  "Afronden zonder oordeel. Alleen: zo is het.",
  "Je bleef bij één ding. Dat is al winst.",
  "Dit is een stille, echte beloning.",
  "Vergeten mag. De taak is bewaard als klaar.",
  "Saai afronden is een veilige smaak.",
  "Je hebt de cirkel rond gemaakt.",
  "Je las de zin tot de punt.",
  "Stoppen was toegestaan. Je nam het.",
  "Dit stuk last is van je schouders.",
  "Je deed het in één ronde. Dat is genoeg.",
  "Gedaan mag blijven liggen als gedaan.",
  "Je aandacht kreeg een thuis en mocht weer gaan.",
  "Je rondde af. Dat mag zacht voelen.",
  "Dit hoeft vannacht niet in ploegendienst.",
  "Eén taak minder die fluistert.",
  "Je koos duidelijkheid. Dat is vriendelijk.",
  "Dit is af, in jouw maat.",
  "Je hebt een einde waar rust op past.",
  "Applaus is niet nodig. Klaar is genoeg.",
  "Je gaf dit de tijd tot het stopte.",
  "Minder herinneren. Meer gedaan.",
  "Je kwam tot hier. Hier is genoeg.",
  "Dit eert je volhouden, niet je tempo.",
  "De stekker mag eruit. Echt.",
  "Je mag opstaan. Dit blijft af.",
  "Je liet het einde gebeuren. Rustig en echt.",
  "Dit telt in het echt, niet op een bord.",
  "Je hebt vandaag al een deur dichtgedaan.",
  "Het is af. Dat mag het enige zijn dat telt.",
];

export const V2_DONE_QUOTES_EN: readonly string[] = [
  "Done is a signal to your brain: this can leave your head.",
  "An open loop is closed. That brings calm, not a score.",
  "Your ADHD brain holds open things extra tight. This one thing is finished.",
  "Finishing is proof that starting was possible.",
  "Your working memory has one less thing to carry.",
  "Completing gives a short, real reward. You can feel that.",
  "It does not have to be bigger. This was enough for now.",
  "You chose, you did, you closed it. That is quietly rare.",
  "Less noise. One task is off the pile.",
  "Your list is lighter. You are too, a little.",
  "This counts because it is done, not because it was impressive.",
  "Your brain can stop reminding you. It is finished.",
  "Follow-through showed up. Once is already a lot.",
  "No more ‘I still have to’. This does not need you.",
  "Finishing is a form of care for yourself.",
  "You gave your attention an ending. That is kind.",
  "The unfinished feeling can stop here.",
  "One closed door in your head. More air.",
  "You did not do it perfectly. You did it. That is the win.",
  "This is evidence against the story that nothing works.",
  "Small finish, big quiet in your head.",
  "Your external memory worked. You did not have to hold it alone.",
  "Done is a feeling, not a number.",
  "Your ADHD looks for new. You chose finish. That is bravely calm.",
  "The task can let you go. Really.",
  "You put an ending on it. Endings are rare and kind.",
  "Fewer open loops. More room to need nothing.",
  "Starting was the hard part. Starting is over.",
  "Your body can notice: it is finished.",
  "Completing is dopamine without a circus.",
  "You are someone who finished this. Today, here.",
  "It may feel boring. Boring-done is still done.",
  "Your head does not have to repeat this tonight.",
  "One less thing pulling at you.",
  "You gave a task an ending. That is structure.",
  "Not more, not less. This is complete.",
  "Your attention had a landing place. And it landed.",
  "The check is not a verdict. It is a fact.",
  "You were allowed to stop. Stopping was the job.",
  "This counts for a brain that wants to move on fast.",
  "You have proof. Not a pep talk.",
  "The day already succeeded in this one thing.",
  "Finishing makes tomorrow a little quieter.",
  "You chose closing over leaving it open forever.",
  "It may feel like nothing. It was still done.",
  "You worked against delay, not against yourself.",
  "A task out of your head is a kind of breathing.",
  "You closed the loop. That is Structuro.",
  "No extra round needed. This can stay finished.",
  "Your ADHD remembers what stays open. This does not stay open.",
  "Finishing is also a skill. You just practised it.",
  "You gave yourself an ending instead of another start.",
  "This is enough to stand up and walk away.",
  "Less guilt about ‘not finished’. This one was.",
  "Your attention got a closing note.",
  "The open tab in your head is closed.",
  "You did it at your pace. And it is done.",
  "Finishing says: I can be trusted with this one thing.",
  "Not everything needs to be done. This did, and that is good.",
  "You may mark this without confetti.",
  "An ending is a gift to your nervous system.",
  "You have less to remember than a minute ago.",
  "This was a choice. Choices that land, calm you.",
  "You went to the end of this small piece.",
  "It can be done without the world changing.",
  "You gave a task rest. You get that rest back.",
  "No half-work in the back of your mind. This is whole.",
  "Finishing is kind to tomorrow-you.",
  "You have a fact: this does not need doing again.",
  "The heavy part was often starting. That is over.",
  "Your brain may switch to nothing, for a bit.",
  "This is not a streak. This is one honest ending.",
  "You pulled something out of the fog and set it down.",
  "Done may feel light. Light is okay.",
  "You kept the promise you made to yourself.",
  "Less ‘later’. More now, finished.",
  "Your ADHD loves new. Finishing is a different reward.",
  "This counts even if nobody saw it.",
  "You gave a piece of chaos an edge.",
  "It can stop. Really stop.",
  "You worked with your brain, not against the clock.",
  "One closed task beats ten open intentions.",
  "You have proof that finishing exists, also for you.",
  "This is a quiet success. Quiet is strong enough.",
  "You can go on without carrying this.",
  "Finishing makes space. No pressure to fill it.",
  "You have an ending you can lean on.",
  "The check says nothing about your worth. Only: done.",
  "You gave attention, and then rest.",
  "This can go in the archive. Not in the worry list.",
  "You chose finishing. That is a friendship with yourself.",
  "One less task shouting for attention.",
  "You already closed a loop today.",
  "It is done, so you may look away.",
  "No extra proof needed. This was the proof.",
  "Your head is a touch quieter. That is the win.",
  "Finishing is not hustle culture. It is finishing.",
  "You took this out of working memory. Good.",
  "This ending is yours. Nobody has to grade it.",
  "Done. That may be the last word.",
  "You gave this thing an ending. That is careful.",
  "Attention that lands is already a compliment.",
  "You stayed until it was done. Short, and real.",
  "This is follow-through, without fireworks.",
  "Your head can close this file.",
  "One task done. No extra story needed.",
  "You chose finishing. You can hear that.",
  "The check is kind, not loud.",
  "You took this out of waiting.",
  "Done may be quiet. Quiet is clear.",
  "You came back to what you promised.",
  "This was enough doing for this moment.",
  "You did not leave the task half open.",
  "Finishing is a quiet form of loyalty.",
  "Your attention had a latch. It closed.",
  "Fewer open endings. That feels cleaner.",
  "You finished it, even without the mood.",
  "This counts for a brain that drops off fast.",
  "You gave chaos a final period.",
  "It can be done. You can believe that.",
  "You already set something down today.",
  "One ending is an anchor, not a stage.",
  "You worked through the hard start.",
  "This is proof that stopping also works.",
  "Your list got rest. You did too.",
  "Finishing without a show. Exactly right.",
  "You did not leave this thing hovering.",
  "What stood open is closed now.",
  "You chose an ending over another start.",
  "This can go with the already-done things.",
  "Your brain gets a short, real pause.",
  "Done. No afterword needed.",
  "You held the thread until it was finished.",
  "This is care for your future self.",
  "You kept a small promise.",
  "This is quiet now. It does not pull.",
  "You gave yourself a soft landing.",
  "It may feel like nothing special. It was still done.",
  "Your ADHD wanted to move on. You stayed until here.",
  "One closed loop. Breathe.",
  "You lifted this out of the fog and put it away.",
  "Finishing is not strict. It is clear.",
  "You can let this go without guilt.",
  "Start to stop: a complete movement.",
  "Your head does not have to keep this.",
  "Being done is a form of kindness.",
  "You put a period where delay put a comma.",
  "Five minutes counts the same as fifty, if it is done.",
  "You took the task to the edge.",
  "Less noise behind your eyes.",
  "You did what you could now. And closed it.",
  "This is not a race. This is an ending.",
  "You gave attention, then a boundary.",
  "The check is a fact, not a star.",
  "You made it to finishing. That is quietly rare.",
  "This may settle you, for a moment.",
  "Fewer open tabs in your day.",
  "The room in your head is a touch bigger.",
  "You did not leave this in the waiting room.",
  "This was enough to stop.",
  "You kept a small contract.",
  "Done. The rest can wait.",
  "Your attention is yours again.",
  "This ending is light, and that is the point.",
  "You worked with what was there. It is done.",
  "Less later. More just-finished.",
  "You gave your nervous system a clear signal.",
  "This counts because you closed it.",
  "You may do something else now, or nothing.",
  "The open feeling stops here.",
  "You set this thing down neatly.",
  "Finishing without a verdict. Only: this is how it is.",
  "You stayed with one thing. That is already a win.",
  "This is a quiet, real reward.",
  "Forgetting is allowed. The task is stored as done.",
  "Boring-done is a safe taste.",
  "You made the circle complete.",
  "You read the sentence to the period.",
  "Stopping was allowed. You took it.",
  "This bit of weight is off your shoulders.",
  "You did it in one round. That is enough.",
  "Done can stay done, not as debt.",
  "Your attention found a home and could leave again.",
  "You finished. That may feel soft.",
  "This does not need a night shift in your head.",
  "One less task whispering.",
  "You chose clarity. That is kind.",
  "This is done, in your size.",
  "You have an ending that rest can sit on.",
  "Applause is not needed. Done is enough.",
  "You gave this the time until it stopped.",
  "Less remembering. More done.",
  "You made it here. Here is enough.",
  "This honours your follow-through, not your pace.",
  "The plug can come out. Really.",
  "You may stand up. This stays done.",
  "You let the ending happen. Calm and real.",
  "This counts in real life, not on a board.",
  "You already closed a door today.",
  "It is done. That may be the only thing that counts.",
];

function pickFromList(list: readonly string[], index: number): string {
  if (list.length === 0) return "";
  const i = ((index % list.length) + list.length) % list.length;
  return list[i] ?? list[0] ?? "";
}

export function pickV2DoneQuote(locale: Locale, index: number): string {
  const list = locale === "en" ? V2_DONE_QUOTES_EN : V2_DONE_QUOTES_NL;
  return pickFromList(list, index);
}

/**
 * Cyclisch: vaste volgorde tot de lijst rond is, daarna weer bij 0.
 * Slaat dezelfde zin over als die twee keer achter elkaar zou komen, tenzij de lijst 1 item is.
 */
export function advanceV2DoneQuote(
  list: readonly string[],
  index: number,
): { quote: string; nextIndex: number } {
  if (list.length === 0) return { quote: "", nextIndex: 0 };
  const quote = pickFromList(list, index);
  let nextIndex = index + 1;
  if (list.length > 1) {
    let guard = 0;
    while (pickFromList(list, nextIndex) === quote && guard < list.length) {
      nextIndex += 1;
      guard += 1;
    }
  }
  return { quote, nextIndex };
}

function readStoredIndex(): number {
  if (typeof window === "undefined") return 0;
  try {
    const raw = window.localStorage.getItem(V2_DONE_QUOTE_INDEX_KEY);
    const n = Number(raw);
    if (Number.isFinite(n) && n >= 0) return Math.floor(n);
  } catch {
    /* privémodus */
  }
  return 0;
}

function writeStoredIndex(index: number): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(V2_DONE_QUOTE_INDEX_KEY, String(index));
  } catch {
    /* privémodus */
  }
}

export function takeNextV2DoneQuote(locale: Locale): string {
  const list = locale === "en" ? V2_DONE_QUOTES_EN : V2_DONE_QUOTES_NL;
  const { quote, nextIndex } = advanceV2DoneQuote(list, readStoredIndex());
  writeStoredIndex(nextIndex);
  return quote;
}
